### ISSUE TITLE
Создать структуру бд

### ISSUE THREAD

**Issue by KogaiIrina** [Move-Fast-and-Break-Things-Study-Group/the-list#1]

**Comment by OstaptsovDanil** [comment]
Что именно значит создать структуру бд?
В mongoDB же нет четкой структуры бд

**Comment by KogaiIrina** [comment]
в Mongo есть коллекции, в коллекциях есть поля.
коллекции могут ссылаться друг на друга.

Создать структуру бд — это значит, что нужно подумать какие коллекции будут в бд, какие поля будут в коллекциях.

**Comment by yurijmikhalevich** [comment]
@OstaptsovDanil, надо описать структуру данных в БД.

Например, в текущей реализации вашего API в #11, вы храните студентов в коллекции `students` в формате:
```
{
  _id: ObjectId,
  name: string,
}
```

Перед тем, как начинать работать над API для посещаемости, вам надо придумать, как вы будете хранить посещаемость.

**Comment by yurijmikhalevich** [comment]
Какие у вас есть идеи?

**Comment by OstaptsovDanil** [comment]
Пока в голове такая вещь
У нас есть коллекция с датами, когда в календаре впервые нажимают на дату, она добавляется в коллекцию. Эта коллекция ссылается на коллекцию студентов, чтобы получить список. В коллекции с датой есть поле для отметки присутствующего true/false

**Comment by OstaptsovDanil** [comment]
Но я пока не знаю как коллекции ссылаются друг на друга, сегодня почитаю

**Comment by Roha990** [comment]
> Пока в голове такая вещь У нас есть коллекция с датами, когда в календаре впервые нажимают на дату, она добавляется в коллекцию. Эта коллекция ссылается на коллекцию студентов, чтобы получить список. В коллекции с датой есть поле для отметки присутствующего true/false

Точно так же думаю

**Comment by yurijmikhalevich** [comment]
Как будет выглядеть `поле для отметки присутствующего true/false`? Сколько записей в БД будет на каждую дату?
```
{
  date: Date,
  // что здесь?
}
```

**Comment by yurijmikhalevich** [comment]
> как коллекции ссылаются друг на друга, сегодня почитаю

Ты можешь сохранить идентификатор записи из одной коллекции в запись в другой коллекции. Чаще всего, сохраняют `_id`. Например, чтобы «сослаться» на конкретного студента в каком-то другом документе в БД, достаточно в какое-то поле в том втором документе записать значение `_id` студента.

**Comment by OstaptsovDanil** [comment]
{
    date: Date,
    //как-то ссылается на студентов,
    be: true/false
}

**Comment by OstaptsovDanil** [comment]
а можно же еще один JSON файл вложить?
```
{
    date: Date,
    {
        //как-то ссылается на студентов,
        be: true/false
    }
}
```

И таких вложенных много по количеству студентов

**Comment by yurijmikhalevich** [comment]
@OstaptsovDanil, хорошая идея. Таким образом, в коллекции **посещаемость** будет одна запись на один день, верно?

Если просто не добавлять туда записи для студентов, которых не было в этот день, можно вообще убрать поле `be`. Тогда, документ может выглядеть вот так:

```js
{
  date: Date,
  presentStudents: [
    ObjectId('abcdf32323232323'),
    ObjectId('abcdf32323232324'),
    ObjectId('abcdf32323232325'),
    ...
  ],
}
```

В `presentStudents` — массив id студентов, которые в этот день присутствовали. Когда надо студента убрать, убираем его id из массива, когда отметить — добавляем.

**Comment by OstaptsovDanil** [comment]
Мне просто кажется, что изменить значение поле be будет проще, чем удалять и добавлять Id студента. Но если удалять отсутствующих, то можно экономить память на сервере

**Comment by yurijmikhalevich** [comment]
@OstaptsovDanil, а что делать, если был добавлен новый студент? Если редактировать все записи для всех дат, то добавление студентов будет супер медленным, а если не редактировать, то надо будет иметь в виду, что в инфе о посещаемости для старых дат может отсутствовать существующий студент, что приводит нас к тому варианту, что я предложил.
