### ISSUE TITLE
Добавить API для вывода посещаемости студентов за текущий день и возможность редактировать посещаемость

### ISSUE THREAD

**Issue by yurijmikhalevich** [Move-Fast-and-Break-Things-Study-Group/the-list#18]
По структуре БД: https://github.com/Move-Fast-and-Break-Things-Study-Group/the-list/issues/1#issuecomment-1265041007

Задачи:
- спроектировать API
- запрограммировать API

@Roha990, @OstaptsovDanil, давайте, сначала, в этом GHI обсудим каким может быть API. Как могут выглядеть запросы и сколько их надо? Какие у вас есть идеи?

**Comment by Roha990** [comment]
Думаю над тем, чтобы список выводился через параметры. Что-то вроде `/students/:date`. Да и думаю над тем, чтобы структура `data` была в структуре `name`.  Будет еще один булевский параметр `visit`, который показывает, был студент в определенный день или нет

**Comment by yurijmikhalevich** [comment]
@Roha990, посещаемость — самостоятельная сущность, предлагаю выделить ей отдельный путь, не запихивать под `/students/`.

Можно сделать так.

Получение инфы о посещаемости:
```
GET /attendance/:date
```
Возвращает список id студентов, присутствовавших в этот день. `id` достаточно, клиент отправит отдельный запрос для загрузки имён студентов, если надо (он должен делать это при запуске сервера в любом случае).

Обновление инфы о посещаемости:
```
PUT /attendance/:date
```
Принимает объект со списком id-шников студентов, присутвовавших в этот день и сохраняет его в БД.

Плюсы:
- просто думать о таком решении
- просто реализовать

Минусы:
В `PUT /attendance/:date` будем вынуждены передавать всех присутствующих студентов даже когда добавляем или удаляем одного.

Думаю, для простоты можно минусом пренебречь. Что ты думаешь?

**Comment by yurijmikhalevich** [comment]
Формат записи в `attendance` может быть тот, к которому ты уже пришёл:
```js
{
  date: string,
  students: [id1, id2, id3, ...],
}
```
