### ISSUE TITLE
Удалить из дизайна бутерброд и доработать дизайн для десктопа

### ISSUE THREAD

**Issue by KogaiIrina** [Move-Fast-and-Break-Things-Study-Group/the-list#3]

**Comment by EmmaMaltseva** [comment]
https://www.figma.com/file/gIHQVcOfB7fsOzjrIYWoY5/Untitled?node-id=0%3A1 Жду комментариев)

**Comment by KogaiIrina** [comment]
@EmmaMaltseva выглядит отлично на мой взгляд! 👍
Расположение компонентов ощущается гармонично.

**Comment by yurijmikhalevich** [comment]
@EmmaMaltseva, мне нравится. Симпатично, аккуратно 😻 

По календарю, кажется, можно слева-справа и снизу отступ сделать чуть больше, иначе получается, что внутренний отступ между цифрами больше, чем внешний. И ещё чёрный квадрат-селектор текущего дня может быть стоит сделать чуть-чуть больше, чтобы было удобнее текущий день выбирать 🤔

Это мои придирки :) Предлагаю, вам утвердить дизайн с командой.

@Move-Fast-and-Break-Things-Study-Group/the-list-core, вы что думаете?

**Comment by yurijmikhalevich** [comment]
Ещё заметил, дни недели с датами не выровнены:
<img width="385" alt="image" src="https://user-images.githubusercontent.com/4187729/193469525-a9124adf-9b6c-4bde-9e96-26df05237cec.png">

**Comment by EmmaMaltseva** [comment]
https://www.figma.com/file/ubUNsNnfOfjTEAXWyM0ySe/Untitled?node-id=0%3A1

![Image](https://user-images.githubusercontent.com/92587254/194776328-23744a2d-e5be-4e81-83c8-55cc08acb2aa.png)

**Comment by yurijmikhalevich** [comment]
@EmmaMaltseva, здорово, спасибо. Календарь теперь мне намного больше нравится 👍

Кажется, что можно ещё попробовать верхние углы у блока с надписью «октябрь» сделать прямыми (как у моноброви на айфоне). Но, в целом, я думаю, можно считать задачу выполненной 🚀

**Comment by KogaiIrina** [comment]
@EmmaMaltseva классный дизайн! :) У меня нет никаких доп пожеланий :+1:

**Comment by Roha990** [comment]
Крутой дизайн👍👍👍

**Comment by yurijmikhalevich** [comment]
Закрываю тикет как сделанный.

**Comment by yurijmikhalevich** [comment]
@OstaptsovDanil, @NSH4R, если есть вопросы или пожелания по доработке, пишите, предлагаю сделать их отдельно :)

**Comment by OstaptsovDanil** [comment]
Нет, мне все нравится
